In [56]:
import numpy as np


In [57]:
# 激活函数： 前向传播需要，反向传播也需要
# deriv 为False表示不求导，为True时表示求导(反向传播)
def sigmoid(x,deriv = False):
    if(deriv == True):
        #这时是反向传播，这里的x代表输出，即sigmod函数，求导就是对sigmod函数求导
        return x*(1-x)
    else:
        #这时直接就是sigmod函数自己
        return 1/(1+np.exp(-x))

In [58]:
# 指定输入和对应的label值（类型）
# 数据的维度是3维的
x = np.array([
    [0,0,1],
    [0,1,1],
    [1,0,1],
    [1,1,1],
    [0,1,0]    
])
x.shape

(5L, 3L)

In [59]:
# 给定输入的label值 神经网络是有监督学习
y=np.array([
    [0],
    [1],
    [1],
    [0],
    [1]
])
y.shape

(5L, 1L)

In [60]:
# 构造神网络的结构  L0->L1->L2  L0输入  L1隐层  L2输出层

## 权重参数W的构造与初始化

In [61]:
# 正向传播：x0*w0 -> x1*w1 -> y
# 反向传播：
# L0层：对应参数W0，输入为3维（列）的，则w0一定是3行，
# 又因为输出为L1层，这里假设L1层有4个神经元，则输出为4列的
# 则w0为3x4

# l2层假设只有一个输出值，对应分类判断[0，1],则同理w1为4x1

w0 = np.random.random((3,4))
w1 = np.random.random((4,1))
# 此时w0, w1为（0，1）区间，希望其为(-1,+1)区间 ：

w0 = 2*np.random.random((3,4))-1
w1 = 2*np.random.random((4,1))-1

w0

array([[-0.89735203,  0.29798364, -0.97961169,  0.22406371],
       [ 0.91849292,  0.28425644, -0.87330526, -0.2862429 ],
       [ 0.31384908, -0.70837014,  0.42788558, -0.62640137]])

## 正向转播与反向传播



![title](img/transposs.png)

In [65]:
for j in xrange(60000):
    #------一次正项传播
    #L0层
    l0=x
    #l1为l0乘权重参数再乘激活函数,参数deriv默认为False表示是前向传播
    l1 = sigmoid(np.dot(l0,w0),deriv=False)
    #同理得l2
    l2 = sigmoid(np.dot(l1,w1),deriv=False)
    #损失值
    error_l2 = y - l2
    #每隔10000次打印出损失值
    #if(j%10000) == 0:
    #print 'error'+str(np.mean(np.abs(error_l2)))
        
    #------一次反向传播更新w的值 error_l2相当于权重项，损失越大，错的越多，要更新的量 delta_l2 就越大
    #这里是对应相乘 因为都是5x1
    delta_l2 = error_l2*sigmoid(l2,deriv=True) #print delta_l2.shape  #print sigmoid(l2,deriv=True).shape
    
    #l1的损失值
    #delta_l2是5x1, w1是4x1,需要对w1转置
    error_l1 = delta_l2.dot( np.transpose(w1))  #print error_l1.shape
    #得l1 的 调整值 delta_l1,即梯度方向:
    delta_l1 = error_l1*sigmoid(l1,deriv=True)
    
    #更新w ，由于之前是  error_l2 = y - l2， 所以这里是+= ， 否则是减等
    w1 += l1.T.dot(delta_l2)
    w0 += l0.T.dot(delta_l1)
    
print w0
print w1

[[-6.11916729 -7.24309022  1.9654356   2.31824582]
 [ 6.98167316  6.51212519  2.02437063 -3.33944326]
 [ 3.11048549 -3.39557428  0.41046595 -1.29077698]]
[[-10.74832159]
 [ 14.14979129]
 [  3.82203088]
 [  4.55112487]]
